### ISSUE TITLE
TypeError: can't iterate from SemanticPuppet::Version

### ISSUE THREAD

**Issue by lazyfrosch** [puppetlabs/semantic_puppet#11]
There seems to be an interesting error with Ruby 2.2.3 + RSpec 3.4.

From what the error suggest it seems to be a problem between rspec and ruby. This issue is mostly meant for reference. It might be related to https://bugs.ruby-lang.org/issues/11113

```
TypeError: can't iterate from SemanticPuppet::Version
./spec/unit/semantic_puppet/version_range_spec.rb:30:in `block (3 levels) in test_range'
```

```
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
Gems included by the bundle:
  * bundler (1.11.0)
  * diff-lcs (1.2.5)
  * rake (10.4.2)
  * rspec (3.4.0)
  * rspec-core (3.4.1)
  * rspec-expectations (3.4.0)
  * rspec-mocks (3.4.0)
  * rspec-support (3.4.1)
  * rubygems-tasks (0.2.4)
```

**Comment by lazyfrosch** [comment]
Any version of Rspec > 3 will fail the tests.

**Comment by scotje** [comment]
Yeah, rspec's "include" matcher seems to have decided that if the collections "include?" method returns false, it needs to try to enumerate the whole collection, which, at first glance, seems wrong? 

Since VersionRanges are infinite (like a floating point range), they are not enumerable. I've got a potential fix worked out though, I'll try to make a PR in a bit.

**Comment by scotje** [comment]
A better solution would probably be to move all the "include" expectations to use the "cover" matcher which is explicitly for ranges.

**Comment by lazyfrosch** [comment]
Thanks @scotje thats a bit too deep of Ruby Voodoo for me :)

**Comment by lazyfrosch** [comment]
Added a PR which fixes the issues in my tests.
